### ISSUE TITLE
Calling start server on same project when server already started fails badly

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio-server#110]
Partially shuts down running server, fails to start new one

Should fail gracefully

**Comment by rHorsey** [comment]
Hmm. Ya. This is ugly. How do I know if a server is running? Once I know what the metric is for that I can very easily make subsequent start_local commands alias to stop_local and then start_local.

**Comment by macumber** [comment]
PAT will need a way to check if there is already a server running for a given project and (potentially) a way to shut it down if the server was left running by mistake (e.g. crash)

**Comment by rHorsey** [comment]
And the server will fail out on start_local if there is a local_configuration.json file in the project directory, and fail out on stop_local if there is not a local_configuration.json file.

**Comment by macumber** [comment]
Do you remove the file if start fails?  I think you should since you try to kill the jobs...

**Comment by rHorsey** [comment]
Hmmm...... Can do.
