### ISSUE TITLE
Some jobs are not shutdown during shutdown

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio-server#111]
Ruby jobs are left running when the server is shut down.  PIDs show up in child_pids list in local_configuration.json but there does not seem to be a call to shut them down.  Command line for these jobs is:

C:/ruby-2.0.0-p594-x64-mingw32/bin/ruby.exe E:/openstudio-server/gems/bin/rails s -p 8080 -P E:/test/test_project/server.pid

Note, the main rails job is shutdown and the webpage does not respond.  I am not sure if this causes the issue but I did run an analysis and then delete it through the website prior to shutdown

**Comment by macumber** [comment]
Simply starting and shutting down server seems to orphan two ruby processes.  These process ids are in the child_pids of local_configuration.json

**Comment by rHorsey** [comment]
I think I have a fix for this. It's also worth noting that this is intermittent on top of everything else. Yay. Specifically, I'm going to wire up command line calls of taskkill instead of Ruby's ::Process.kill for windows. I'll let you know when I have a PR.

**Comment by macumber** [comment]
Cool, just an FYI for now, it does seem the server is taking longer to start up on Windows, my suspicion is that this is time used for the WMIC command, we should make sure that we are making command line calls judiciously

**Comment by rHorsey** [comment]
It's always taken way way way longer on windows. Do you mean noticeably longer than before? Either way, let's make a 'Profile the !@#$%^&*() out of the Windows server start process' ticket for later.
