### ISSUE TITLE
End time and duration of Analysis incorrect

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio-server#116]
The end time on an analysis isn't correct, so the duration isn't correct.

Here's the summary:
![image](https://cloud.githubusercontent.com/assets/2009290/20580143/fa8b78e8-b18d-11e6-8fa8-e6eb51d9dc43.png)

But here are the datapoints.  Clearly more than a minute.
![image](https://cloud.githubusercontent.com/assets/2009290/20580120/db0d818c-b18d-11e6-8d9e-6a9b187b361b.png)

**Comment by shorowit** [comment]
Note that the End time and Duration are filled out even while the analysis is in the middle of running.

**Comment by rHorsey** [comment]
Fixed somewhere along the line by @nllong - Thanks!!!
