### ISSUE TITLE
datapoint.zip files won't open on windows

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio-server#123]
PAT isn't downloading the datapoint.zip files correctly on windows.  It appears that this is because the files cannot be opened correctly, not because they don't exist on the server.

Here's the PAT log:
![image](https://cloud.githubusercontent.com/assets/2009290/20986985/18706f30-bc88-11e6-9a88-fa2e11ce5b48.png)

After manually downloading the datapoint.zip from the server, here's the error on open:
![image](https://cloud.githubusercontent.com/assets/2009290/20986847/7a06ff1c-bc87-11e6-9772-a0c0a6aa98e0.png)

**Comment by asparke2** [comment]
@macumber: @henryHorsey indicated that you would be the right person to fix this.  @kflemin FYI.

**Comment by rHorsey** [comment]
@macumber When I started digging down into the WFG I think https://github.com/NREL/OpenStudio-workflow-gem/blob/osw/lib/openstudio/workflow/adapters/output_adapter.rb#L84-L110 is the code being invoked, which looks to be the OpenStudio Zip library. I thought this worked before, however, which is what has me a little confused.

**Comment by asparke2** [comment]
@henryHorsey:  @macumber and I looked at something which makes him think it isn't an issue with the zip library.

I went into the `/temp_data/analysis_xyz/data_point_abc/run` directory and compared the datapoint.zip there with the datapoint.zip I manually downloaded from the server web interface.

![image](https://cloud.githubusercontent.com/assets/2009290/20989176/fddc3952-bc90-11e6-8904-e1ccfdce2f5b.png)

The one I accessed directly through `/temp_data` opens fine and actually contains stuff (7318 KB), whereas the one from the server is 2 KB and doesn't open.  So maybe the server isn't serving it up correctly?

**Comment by rHorsey** [comment]
@asparke2 @macumber I think this is something @nllong mentioned in passing to me a few months back; thanks for the debug! This is a windows only issue, right?

**Comment by asparke2** [comment]
@henryHorsey Yeah I think it is Windows-only; david was able to download and open the datapoint.zip successfully.

**Comment by rHorsey** [comment]
@asparke2 Can you test with a9fb663? (Just pull dockerize.) This should fix binary read errors on Windows.

**Comment by rHorsey** [comment]
Confirmed by @asparke2. Closing
