### ISSUE TITLE
enforce unique measure names in analyses

### ISSUE THREAD

**Issue by nllong** [NREL/OpenStudio-server#14]
Right now in order to enforce unique names, the variable/measure UUID is used instead of enforcing unique names.
32487a90-45c4-0132-c73b-14109fdf0b37.projection_factor: {

**Comment by lgentile** [comment]
@nllong @rHorsey still an issue to be dealt with?

**Comment by rHorsey** [comment]
Is this still a thing?

**Comment by kflemin** [comment]
this is enforced in PAT
