### ISSUE TITLE
Bugs with pagination

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-server#172]
I've run a diagonal analysis with 100 datapoints. 50 are displayed on the first page and it says there are 4 pages instead of 2. Additionally, all 4 pages show datapoints 1-50, so I can only see the rest of my datapoints by clicking 'View All'.

![1](https://cloud.githubusercontent.com/assets/5861765/25586923/e4c11a42-2e5e-11e7-9a5c-a9e144accb01.png)

![2](https://cloud.githubusercontent.com/assets/5861765/25586924/e5fd71ee-2e5e-11e7-955d-cbe64e0674bc.png)

![3](https://cloud.githubusercontent.com/assets/5861765/25586929/e8cb3b54-2e5e-11e7-84b9-ecbe56cb39e1.png)

**Comment by rHorsey** [comment]
@shorowit Can you move this over to OpenStudio's issue list? I think it's a major-bug; two notes, first I only see it after the analysis is completed, and second it's not just the Name field, its the entire row of data.
