### ISSUE TITLE
Pareto Front Calculation Fails

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio-server#205]
Trying to generate a Pareto Front for data like this:

![psogas](https://user-images.githubusercontent.com/2230150/30492272-c5e1d150-99f4-11e7-803c-3701932c6ee5.png)

Results in the "Something Went Wrong" page.  This happens with multiple algorithms and variable choices.

**Comment by kflemin** [comment]
@ljbrackney, can you provide an analysis where this happens?  thanks!
