### ISSUE TITLE
OS Server Dies Mid-Analysis

### ISSUE THREAD

**Issue by rHorsey** [NREL/OpenStudio-server#241]
_From @ljbrackney on August 28, 2017 14:22_

UCI Partner was running an optimization - presumably with 2.2.0 on AWS.  rgenoud was making progress for a while then rolled over and died.

![view_analysis1](https://user-images.githubusercontent.com/2230150/29777575-63717c14-8bc1-11e7-82f6-664ebb3acc38.PNG)

![view_analysis2](https://user-images.githubusercontent.com/2230150/29777579-689c56c8-8bc1-11e7-87a4-8fee6d9ef4b8.PNG)

Is this a known issue that was fixed for 2.2.1?  I will be getting the project this morning for further debug.

_Copied from original issue: NREL/OpenStudio#2758_

**Comment by rHorsey** [comment]
_From @brianlball on August 28, 2017 15:5_

do we know what instance they were using?  its possible it ran out of storage if its a small instance.

**Comment by rHorsey** [comment]
_From @ljbrackney on August 28, 2017 15:7_

I don't know.  We can ask this afternoon, but in the meantime I'm just going to roll on 24a to get rolling.

**Comment by lgentile** [comment]
@rHorsey is this still a blocker?

**Comment by rHorsey** [comment]
I don't know what to do with this one. There's a feature request here around preemptively stoping everything if the disk ever gets above 90% full. I'll make a feature request for that.
