### ISSUE TITLE
Fix list of nodes on the compute tab

### ISSUE THREAD

**Issue by rHorsey** [NREL/OpenStudio-server#242]
_From @rHorsey on July 26, 2017 20:38_

This will be particularly useful when we implement health checks.

_Copied from original issue: NREL/OpenStudio#2703_

**Comment by rHorsey** [comment]
Waiting for ComStock funding for @nllong to address this issue.

**Comment by rHorsey** [comment]
Reclassifying this as a feature, as it needs to be developed from scratch with Redis / resque given current design plans.

**Comment by anyaelena** [comment]
Per Kat, nodes are not showing up on OpenStudio Server nodes tab.
