### ISSUE TITLE
Scatter Plot on Server Contains Extraneous Data

### ISSUE THREAD

**Issue by rHorsey** [NREL/OpenStudio-server#243]
_From @ljbrackney on June 27, 2017 17:6_

Scatter Plots on the server are cluttered with several non-useful values that make it hard to use.  Please remove _id, name, run_start_time, run_end_time, status, status_message from this plot.  This is borderline between minor bug and feature request, and is low priority.

_Copied from original issue: NREL/OpenStudio#2679_

**Comment by kflemin** [comment]
Fixed in https://github.com/NREL/OpenStudio-server/pull/262.  Awaiting merge...
