### ISSUE TITLE
PAT 2.3.0 on Windows - Local Server Not Starting - Server Error

### ISSUE THREAD

**Issue by rHorsey** [NREL/OpenStudio-server#251]
_From @DrNick13 on November 21, 2017 4:29_

PAT 2.3.0 is consistently not starting on opening a Project. Stopping/restarting the server sometimes reconnects the Local Server, but does not reliably reconnect. Ruby processes and mongod are opening, but look to be timing out and not starting.

On start-up:

![image](https://user-images.githubusercontent.com/33544587/33054494-9d4a05ce-cecd-11e7-999a-6a2c190737a0.png)

On attempted Local Run:
![image](https://user-images.githubusercontent.com/33544587/33054560-1241284e-cece-11e7-8d83-e8838839e663.png)

On Server Restart attempts:
![image](https://user-images.githubusercontent.com/33544587/33054940-acfd19b8-ced0-11e7-9b0d-d2f1ad06fb17.png)

_Copied from original issue: NREL/OpenStudio#2857_

**Comment by lgentile** [comment]
Is this still happening?

**Comment by DrNick13** [comment]
Confirming these errors are still occurring.

**Comment by anyaelena** [comment]
Closing.  Please re-open if this issue occurs for current versions of PAT (>= 2.6.0).
