### ISSUE TITLE
Filtered Datapoints Listed Below Parallel Coordinates Plot Are Wrong

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio-server#258]
When applying filters to parallel coordinate plots to identify solutions that match criteria, the downselected points below the plot may or may not fall within filtered ranges.  An example...

![filter](https://user-images.githubusercontent.com/2230150/35066150-7e131004-fb84-11e7-8797-63a5ee1df4a3.png)

This renders that feature unusable, and it's hard to find points you're after.

**Comment by ljbrackney** [comment]
Also the number of selected datapoints does not always appear to match the selection.  I've filtered down to what should have been a single datapoint, but the list still shows a half dozen or more - most of which don't fit the criteria.

**Comment by kflemin** [comment]
Fixed in https://github.com/NREL/OpenStudio-server/pull/262.  Awaiting merge...

**Comment by DavidGoldwasser** [comment]
![screen shot 2018-03-09 at 11 45 24 am](https://user-images.githubusercontent.com/4857055/37224000-760c642c-238f-11e8-8e33-2189fbeb3241.png)

@kflemin do you know if this has been deployed on 24b? I still see to many datapoints when I filter across more than one column?

**Comment by kflemin** [comment]
@DavidGoldwasser, I'm not sure...it might not be.

**Comment by DavidGoldwasser** [comment]
Confirmed this is working, 24a and 24b just not updated to use latest code yet
