### ISSUE TITLE
Enable dynamic installation of OpenStudio packages

### ISSUE THREAD

**Issue by rHorsey** [NREL/OpenStudio-server#267]
Currently packages have to be installed, and then the critical ruby bindings and static objects re-zipped to allow for new OpenStudio versions to be tested. The desired behavior looks like https://github.com/NREL/OpenStudio-server/blob/6e1d32d20aee548755dacbcefd85c52b0810f2a8/ci/travis/setup.sh#L11-L23, however that approach requires integration of the QTCLI. @axelstudios has already done this, however it needs to be integrated into the CI process for this repo for the tests to be updated as desired.

**Comment by rHorsey** [comment]
@axelstudios Can you link one of your example QTCLI scripts here for @nllong please? Thanks!

**Comment by axelstudios** [comment]
Here's one: https://github.com/NREL/OpenStudio/blob/develop/install.qs

**Comment by nllong** [comment]
This is only true for the windows packages, correct?

**Comment by axelstudios** [comment]
@nllong Right, currently only the Windows installer is QtIFW (Ubuntu uses .deb packages, and Mac uses .zip with the .app inside)

**Comment by macumber** [comment]
Can we get some documentation on this under like "Automated Installation" on this page http://nrel.github.io/OpenStudio-user-documentation/getting_started/getting_started/ ?

We literally got another email about this 5 minutes ago

**Comment by nllong** [comment]
Looks like this has been done-- https://github.com/NREL/OpenStudio-server/blob/develop/ci/appveyor/setup.cmd#L5. @henryHorsey can you verify that this is what you wanted?

**Comment by nllong** [comment]
for mac we have to do this: https://github.com/NREL/OpenStudio-server/blob/241-develop-fix-tests/ci/travis/setup.sh#L15-L18

**Comment by axelstudios** [comment]
Ah, good to know.  I wasn't aware that the .app inside the mac zip was actually just an installer

**Comment by kbenne** [comment]
Assuming OpenStudio ci comes online, what about just asking it to make a tar or zip package in addition to the ifw (Qt installer - which is what the zip with a .app installer inside is)? EnergyPlus does this. GUI installers with options, path setup etc for humans, straight tarballs for automated computer stuff. We grab the tarballs to pull E+ into OpenStudio for instance. 

https://github.com/NREL/EnergyPlus/releases/tag/v8.9.0-TestTeXFix
