### ISSUE TITLE
Move openstudio installation directory to /projects on AppVeyor

### ISSUE THREAD

**Issue by rHorsey** [NREL/OpenStudio-server#268]
Currently openstudio is installed to `C:/openstudio` on AppVeyor, however it needs to be installed to `C:/projects/openstudio` to comply with AppVeyor recommended procedures. This doesn't appear to impact build success, however conformation is probably worth while in this case, given how abruptly the c drive is updated.

**Comment by anyaelena** [comment]
It looks like this install.qs script from the OpenStudio repo installs to C:/openstudio.  Do you want me to just move the directory after it is installed and update that RUBYLIB path as well?
