### ISSUE TITLE
Migrate to the openstudio CLI

### ISSUE THREAD

**Issue by rHorsey** [NREL/OpenStudio-server#269]
This is required to support custom gems on the server. Currently the workflow gem is used, see https://github.com/NREL/OpenStudio-server/blob/develop/server/app/workers/run_simulate_data_point.rb#L169-L183. This needs to be replaced with a well mannaged spawned process with identical output log name and file structure. I'd recommend starting with https://github.com/NREL/OpenStudio-server/blob/develop/bin/resources/local.rb#L252-L271 and adapting appropriately. Of particular note, we probably shouldn't timeout the call.

**Comment by nllong** [comment]
Here is the CLI documentation: https://nrel.github.io/OpenStudio-user-documentation/reference/command_line_interface/

**Comment by nllong** [comment]
Any reason not to use popen instead of system call? I prefer [this](https://github.com/NREL/OpenStudio-workflow-gem/blob/91a30cd5bfcd407c9aac0be6077d4fe1a3bc2d07/lib/openstudio/workflow/util/energyplus.rb#L120-L124)

**Comment by anyaelena** [comment]
is the intention to leave workflow gem calls in place but add another value for this [:run_workflow_method](https://github.com/NREL/OpenStudio-server/blob/develop/server/app/workers/run_simulate_data_point.rb#L46)  to indicate CLI?   Does not appear to be used currently?

**Comment by nllong** [comment]
I suggest removing the run_workflow_method. It was an old method and it probably is not being used anymore.

**Comment by anyaelena** [comment]
It looks like for results, including completed_status, i'll need to parse the out.osw file generated by the CLI.  Is that your understanding as well?

**Comment by nllong** [comment]
Yes that is true. I am not sure if there is a helper library out there yet.
I can ask around.

**Comment by anyaelena** [comment]
Ok.  Running via CLI, there is an error finding EnergyPlus.   This is from run.log generated via CLI call `openstudio run --workflow #{osw_path} --debug`.  I'll keep investigating, but putting this out there in case it's clear to one of you.

````
[16:59:11.765392 ERROR] /usr/local/lib/ruby/gems/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/util/energyplus.rb failed with Unable to find the EnergyPlus executable, /usr/local/lib/ruby/gems/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/util/energyplus.rb:18:in `find_energyplus'
/usr/local/lib/ruby/gems/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/util/energyplus.rb:94:in `call_energyplus'
/usr/local/lib/ruby/gems/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/jobs/run_energyplus.rb:44:in `perform'
/usr/local/lib/ruby/gems/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/run.rb:261:in `step'
/usr/local/lib/ruby/gems/2.2.0/gems/openstudio-workflow-1.3.2/lib/openstudio/workflow/run.rb:210:in `run'
:/openstudio_cli.rb:821:in `execute'
:/openstudio_cli.rb:620:in `execute'
:/openstudio_cli.rb:1547:in `<main>'
eval:85:in `eval'
eval:85:in `require_embedded_absolute'
eval:70:in `block in require'
eval:64:in `each'
eval:64:in `require'
````

**Comment by macumber** [comment]
Related to this: https://github.com/NREL/OpenStudio/issues/2911

For now when you call openstudio, use the full path to invoke it: 

    /usr/bin/openstudio run --workflow #{osw_path} --debug

**Comment by anyaelena** [comment]
Thanks Dan!

**Comment by anyaelena** [comment]
Working in Travis,  working through AppVeyor errors:

@macumber the CLI should run `openstudio.exe run --workflow #{osw_path} --debug` on Windows, correct?  No path prefix required?

@rHorsey @nllong i'm getting a bunch of these [permission denied errors](https://ci.appveyor.com/project/rHorsey/openstudio-server/build/1.0.1495-270-241-develop#L1891).  recognize them?   I don't see an obvious relationship with my code change.

@rHorsey @nllong for now, i'm just calling CLI directly using backticks.  I did have popen working but didn't see a need since we don't need access to stdin/stdout.  However, there's no timeout, hung process handling now.  I can change as youall see fit, given your understanding of how issues may arise.

Thanks and sorry this has taken so long!

**Comment by macumber** [comment]
The path issue wasn't a problem on Windows but never hurts just in case

**Comment by nllong** [comment]
The permission denied errors do not ring a bell on my end. 

Calling via backticks sound reasonable. I think we want a timeout, but have no idea on the length of that timeout, 1 hour would be too low, 4 hours would be pointless. So maybe 2 hours? @rHorsey

**Comment by anyaelena** [comment]
Sorry, there may be a bit more delay while I figure out a debugging strategy for this on Windows.

**Comment by rHorsey** [comment]
@anyaelena I have feelings about backticks vs exec vs spawn vs popen, but I fully support backticks in this case.

@nllong @anyaelena I don't think we should timeout, mostly because there are real E+ models for very very real projects that take 20 hours to run, and I think the outcomes might be better if the engineering analysis could be dusted with rgenound magic for that extra 1-10%. This is a demonstrably bad answer, however. Honestly, I've been trying to avoid this issue for over a year. Anya, could you meeting-request me and @nllong to talk about this for 15 minutes?

**Comment by anyaelena** [comment]
Adjusting to 4 hour timeout (per @asparke2 i am told)

**Comment by anyaelena** [comment]
As discussed the @nllong and @rHorsey this assumes that the openstudio executable can be found in PATH.
