### ISSUE TITLE
Get Ubuntu unit tests passing

### ISSUE THREAD

**Issue by rHorsey** [NREL/OpenStudio-server#272]
Currently the bundle environment on Travis is not loading dependencies as required. Additionally, no integration tests are run. If we are supporting PAT on Ubuntu, the integration tests passing on Ubuntu on Travis are critical.

**Comment by anyaelena** [comment]
May not be source of failure, but I've noted a couple things:

Travis setup seems to be hardcoded to different versions of OpenStudio for [OSX](https://github.com/NREL/OpenStudio-server/blob/develop/ci/travis/setup.sh#L11) vs [Ubuntu](https://github.com/NREL/OpenStudio-server/blob/develop/ci/travis/setup.sh#L29).  Should i move these into Env vars in the travis.yml?  What version/sha do we mean to use?

Also, the RUBYLIB var for Ubuntu is using system Ruby (/usr/Ruby) whereas OSX uses a Ruby path [within the openstudio install directory](https://github.com/NREL/OpenStudio-server/blob/develop/ci/travis/setup.sh#L15). We are doing something similar with AppVeyor - are we actually installing Ruby as part of the OpenStudio download?  That seems surprising.  I also jumped on my local Docker image which seems to be built using the same [install_openstudio.sh](https://github.com/NREL/OpenStudio-server/blob/develop/docker/deployment/scripts/install_openstudio.sh) script as our Ubuntu build, and i don't see /opt/openstudio/Ruby or /mnt/openstudio/Ruby...

**Comment by rHorsey** [comment]
Insofar as your first comment is concerned, that is a definite thing - see #267 

For rubylib... That's strange. It should be in the form of `export RUBYLIB=/path/to/openstudio/ruby:$RUBYLIB` which would explain some issues, but not why any of the gems can't be found. If openstudio can't be found, the problem normally shows up as `require 'openstudio-analysis'` erring out.

**Comment by anyaelena** [comment]
Hmm that deb actually unpacks to /usr so /usr/Ruby is the Ruby version installed with OpenStudio.

I'm not sure how /opt/openstudio and /mnt/openstudio dirs + contents are created but i'll leave that alone for now.

**Comment by anyaelena** [comment]
the BUNDLE_GEMFILE var is being stomped on [here](https://travis-ci.org/NREL/OpenStudio-server/jobs/344862824#L792), it looks like part of rvm setup?  It is looking at Gemfile in root of repo (see [BUNDLE_GEMFILE](https://travis-ci.org/NREL/OpenStudio-server/jobs/344862824#L1337) and [bundle list](https://travis-ci.org/NREL/OpenStudio-server/jobs/344862824#L1340)).  I fixed by explicitly setting BUNDLE_GEMFILE before running tests.  Will do a little cleanup and submit PR.

**Comment by rHorsey** [comment]
Yay!!! Thanks @anyaelena !!!
