### ISSUE TITLE
Migrate Circle test/deploy to Travis

### ISSUE THREAD

**Issue by rHorsey** [NREL/OpenStudio-server#274]

**Comment by nllong** [comment]
I did this and then reverted it all. Travis build time out reached. Could fix by having nice layers predefined.

**Comment by rHorsey** [comment]
!@#$%^&*()_+~{}|:"<>?

**Comment by nllong** [comment]
start at layering. https://github.com/NREL/OpenStudio-server/blob/241-develop/Dockerfile#L6

**Comment by nllong** [comment]
and this: https://hub.docker.com/r/nrel/openstudio-r/tags/
