### ISSUE TITLE
Fix `require 'resque'` in rspec tests for Travis

### ISSUE THREAD

**Issue by rHorsey** [NREL/OpenStudio-server#289]
https://travis-ci.org/NREL/OpenStudio-server/jobs/346435676

For some reason, the switch at https://github.com/NREL/OpenStudio-server/blob/241-develop/server/config/initializers/default_config.rb#L66 isn't triggering to prevent evaluation of `require 'resque'` leading to the current error seen in the linked travis failure. I suspect an env var.

**Comment by rHorsey** [comment]
This is also currently breaking the Circle CI tests! Yay! A single error!

**Comment by anyaelena** [comment]
it looks like you just want me to add "test" to the environments we check for in that switch and also [here](https://github.com/NREL/OpenStudio-server/blob/241-develop/server/app/workers/run_simulate_data_point.rb#L442) and maybe a couple other places.

But just to confirm - we aren't testing this redis/resque integration with our unit testing?  

Resque is only included in [Gemfile](https://github.com/NREL/OpenStudio-server/blob/241-develop/server/Gemfile#L92) for docker and production environments

**Comment by nllong** [comment]
Redis/Resque is tested on Docker via circleci. The Travis tests are testing the deployment for local development, which should only use delayed_jobs.

**Comment by anyaelena** [comment]
The 'test' environment is not included in any of the Rails.env checks that determine DelayedJob instead of Resque.

To fix this, i suggest that rather than updating all these to include checks for Rails.env == 'test':

1) Override this [job adapter variable](https://github.com/NREL/OpenStudio-server/blob/289-241-develop/server/config/application.rb#L26) to be :resque in the config/environment/ files for environments that use Resque. (Side note - I don't see that we are using ActiveJob - should i just replace this with `config.job_manager = :delayed_job` ?)
2) replace the explicit `Rails.env == 'whatever'` if/else blocks that determine whether we use Resque with a check on config variable:
````
if Rails.application.config.active_job.queue_adapter == :delayed_job
// Delayed job code
elsif Rails.application.config.active_job.queue_adapter == :resque
//Resque code
else
//raise error
end
````

**Comment by nllong** [comment]
That sounds good to me!

**Comment by nllong** [comment]
@anyaelena -- have you implemented your change yet? I am working on getting the tests to work in both delayed_job and resque and this would be helpful.

And yes, we aren't using ActiveJob because we really aren't using the config.job_manager AFAIK.

**Comment by anyaelena** [comment]
@nllong ci running now for the change

**Comment by anyaelena** [comment]
@nllong  it looks like this change may be working as expected but build still [failed](https://travis-ci.org/NREL/OpenStudio-server/jobs/351556596#L2170).  

you can pull branch (289-241-develop) into 241-develop if you want my changes.

**Comment by anyaelena** [comment]
@nllong so travis is running with test environment and i originally did all this to set up test to run using delayed_job (see above).

All that to say, if test uses resque i may not have fixed the issue.

**Comment by nllong** [comment]
I’m fixing that right now. I am testing both resque and delayed_job in the
spec. I’m also making the jobs run immediately (eager) during tests instead
of the hacky threads I had in there.

Thanks for your help on this. Having the config.job_manager is much better
and made the changes to the tests easier.
