### ISSUE TITLE
Determine why Mac and Windows builds now require the "--with_test_develop" flag to be set

### ISSUE THREAD

**Issue by evanweaver** [NREL/OpenStudio-server#290]
Using this flag nearly doubles package size, so it would be nice to remove it.

**Comment by rHorsey** [comment]
RUBOCOP!!!!! WHY DO YOU HATE ME SOOOOOOO. @nllong lol - my relationship with rubocop is really really bad...

**Comment by rHorsey** [comment]
See #293

**Comment by rHorsey** [comment]
Resolved by #293
