### ISSUE TITLE
When unzipping data_point.zip files on Windows, multiple files exist

### ISSUE THREAD

**Issue by nllong** [NREL/OpenStudio-server#309]
### General Issue / Feature Information

**Description**

When downloading a data_point.zip file on windows and unzipping the unzipper sees duplicate files (at least 3). This does not appear to happen on mac nor linux.

**Reproduction steps:**
1. Run a simulation.
2. Download a data_point zip file on Mac, unzip, and check that only one copy of the data exist in the measures folder.
3. Download the same data-point zip file on Windows, unzip and you will see an error pop up and 3 duplicates of data

**Actual outcome:**
See above

**Expected outcome:**
Only one copy of file in zip file. Not sure if this is bloating the filesize, probably not, but there seems to be an issue with the configuration of the zip for windows.

**Other information (i.e. issue is intermittent):**

![screen shot 2018-03-15 at 10 56 38 am](https://user-images.githubusercontent.com/1907354/37478647-6df58bc8-2840-11e8-8f76-ceb49e193053.png)
![screen shot 2018-03-15 at 10 56 26 am](https://user-images.githubusercontent.com/1907354/37478648-6e544b54-2840-11e8-99e9-a1ccf4ddbfda.png)

**Comment by nllong** [comment]
https://github.com/NREL/OpenStudio-workflow-gem/blob/5adaefd538fdbec9a521b736bfe9cc6a9478afc9/lib/openstudio/workflow/adapters/output_adapter.rb#L88

**Comment by nllong** [comment]
Example data point zip file: https://s3.amazonaws.com/openstudio-resources/server/debug/data_point.zip

**Comment by rHorsey** [comment]
ping @macumber

**Comment by macumber** [comment]
Is the zip file generated on Windows or Unix?  I am not clear what you mean by multiple files of the same name, the operating system does not allow that?

**Comment by macumber** [comment]
Also, what is this blocking?

**Comment by macumber** [comment]
I'd bet the file glob pattern '**' on this line: https://github.com/NREL/OpenStudio-workflow-gem/blob/5adaefd538fdbec9a521b736bfe9cc6a9478afc9/lib/openstudio/workflow/adapters/output_adapter.rb#L72 is causing files in the directory to be added multiple times

**Comment by nllong** [comment]
It is only on windows that the zips from Linux show up. See the image.
There are 3 of the exact same files.

**Comment by nllong** [comment]
makes sense, glob pattern should probably just be `Dir[File.join(local_directory.to_s, '*')]`... since the directories will be recursively added.

**Comment by eshadd** [comment]
I have this same issue except that indeed, I do see two to three copies on Linux (lubuntu 14.04). I run on lubuntu and open in lubuntu.

**Comment by brianlball** [comment]
if this is still an issue then reopen
