### ISSUE TITLE
Variable for plot_xy_interactive use the the measure option name and arg name instead of output display name

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio-server#321]
### General Issue / Feature Information

**Description**

When I setup "Outputs" in PAT on the outputs tab with both "Display Name" and "Short Name" the interactive XY plot does not reflect these names. Since I'm using a measure that has been copied about 20 times "measure_name.arg_name" isn't useful. Notice under expected outcome that parallel coordinates plot doesn't exhibit this issue.

**Reproduction steps:**
1. Copy a measure instance many times
2. Add output variables for multiple measures instances
3. Run algorithmic analysis

**Actual outcome:**

![screen shot 2018-04-02 at 1 48 51 pm](https://user-images.githubusercontent.com/4857055/38213255-d3ddcd1a-367d-11e8-814b-f4da6345313f.png)

**Expected outcome:**

![screen shot 2018-04-02 at 1 48 16 pm](https://user-images.githubusercontent.com/4857055/38213264-d8f24d3a-367d-11e8-8ea2-9690c076eca9.png)

**Other information (i.e. issue is intermittent):**

NA

### Meta-CLI / PAT Server Fails to Launch Details

**Client operating system version:**

NA - On NREL24b

**OpenStudio Meta-CLI providence**

Using PAT 2.4.1 on NREL 24b

**Comment by DavidGoldwasser** [comment]
This also affects the results.csv, which I know is something we may not want to change. For my use case I can always open the "pat.json" and find/replace the name. Maybe feature request for PAT could have the "name" update to follow the user entered "Display Name"?

**Comment by rHorsey** [comment]
Assigning this to @kflemin, although I don't expect it to be closed in the near future.
