### ISSUE TITLE
OS-Server fails to build AMI because tag called latest for Mongo was not found

### ISSUE THREAD

**Issue by padmassun** [NREL/OpenStudio-server#342]
@rHorsey @anyaelena @phylroy 

#### Problem:
The AMI creation fails because it was not possible to find the tag called `latest` for both _**MongoDB**_ and _**Redis**_, when the script attempts to push the MongoDB and Redis image (from dockerhub) into the local docker registry (localhost:5000)

When the repository is pulled from the dockerhub, the image for mongo is listed as:
```
REPOSITORY                 TAG                    IMAGE ID            CREATED             SIZE
...
...
registry                   2.6                    d1fd7d86a825        4 months ago        33.3MB
mongo                      3.4.10                 e905a87e116d        5 months ago        360MB
```

When calling `docker tag mongo localhost:5000/mongo` Docker looks for the mongo image with the `latest` tag which cannot be found.

#### Solution
This problem can be solved by specifying the tag of the image downloaded from dockerhub which will be tagged as latest when pushing that image into the local docker registry. 

```bash
docker tag mongo:$MONGO_VERSION localhost:5000/mongo:latest
```

The file changes needed to complete this are present at https://github.com/NREL/OpenStudio-server/pull/341

**Comment by brianlball** [comment]
@nllong fyi

**Comment by nllong** [comment]
I think we should lock down the versions of mongo and redis

**Comment by padmassun** [comment]
Resolved on nrcan's side with (https://github.com/NREL/OpenStudio-server/pull/341)

**Comment by nllong** [comment]
Resolved on nrel side as well! Thanks @padmassun
