### ISSUE TITLE
Full integration test set up in Travis

### ISSUE THREAD

**Issue by anyaelena** [NREL/OpenStudio-server#358]
Test Docker deployment with worker, web_background, and web containers.  Current CircleCI testing runs all queues on web container.

**Comment by rHorsey** [comment]
`resque:run_simulate_datapoint_spec` tests this.

**Comment by rHorsey** [comment]
nvrmind.

**Comment by anyaelena** [comment]
We do test the resque workflow in two specs [here](https://github.com/NREL/OpenStudio-server/tree/develop/server/spec/features).  We may decide to skip this task and instead focus on more rigorous regression testing on a dedicated machine using [test cases](https://github.com/NREL/OpenStudio-PAT/tree/develop/sample_projects) in PAT repo.

**Comment by anyaelena** [comment]
removing "in Travis" from title.  we may do integration/regression/algorithm testing all at once by running the examples from PAT repo

**Comment by anyaelena** [comment]
closing in favor of #481
