### ISSUE TITLE
workflow gem should be removed from server/Gemfile

### ISSUE THREAD

**Issue by anyaelena** [NREL/OpenStudio-server#390]
we are getting CI test failures on both appveyor and travis when this is removed.  See commits/build results on this [PR](https://github.com/NREL/OpenStudio-server/pull/389)

**Comment by anyaelena** [comment]
run_simulate_datapoint has a call to Workflow.extract_archive which will need to be replaced before this dependency is gone.

**Comment by brianlball** [comment]
reopen if necessary
