### ISSUE TITLE
Internal 2.6.2 OpenStudio mac installer can't find standards gem

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio-server#394]
Here is the error I see on local run when trying to use the standards gem.

"[10:41:38.077046 ERROR] /Applications/OpenStudio-2.6.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/openstudio-workflow-1.3.3/lib/openstudio/workflow/util/measure.rb failed with message cannot load such file -- openstudio-standards in /Applications/OpenStudio-2.6.2/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:292:in `require'

**Comment by anyaelena** [comment]
nick added a test for this, but we've been unable to reproduce the error.

**Comment by nllong** [comment]
I think I need to understand how you are running the analysis a bit better. Let's chat this week.

**Comment by DavidGoldwasser** [comment]
@nllong I was doing a local manual run from PAT in workflow that had measures that required openstudio-standards.

**Comment by rHorsey** [comment]
This ticket is a manifestation of a merge error which lead to the CLI not being used - this is being resolved in https://github.com/NREL/OpenStudio-server/pull/393

**Comment by rHorsey** [comment]
We believe that this is fixed in the most recent 2.6.2 candidate. @DavidGoldwasser can you please confirm.

**Comment by rHorsey** [comment]
lgtm
