### ISSUE TITLE
nokogiri error on travis (ubuntu/osx)

### ISSUE THREAD

**Issue by anyaelena** [NREL/OpenStudio-server#398]
https://travis-ci.org/NREL/OpenStudio-server/jobs/427382134#L5178 only on "test" builds

**Comment by anyaelena** [comment]
confirmed that we're seeing this error on passing "integration" builds as well: https://travis-ci.org/NREL/OpenStudio-server/jobs/427402248#L2004

**Comment by rHorsey** [comment]
We believe this has been fixed with #407
