### ISSUE TITLE
Sobol method plots

### ISSUE THREAD

**Issue by agonzalezesteve** [NREL/OpenStudio-server#422]
Using the Sobol method for sensitivity analysis doesn't draw plots with the results (compared to Morris and FAST99 methods).

![image](https://user-images.githubusercontent.com/38532229/47207894-bdeb5980-d38c-11e8-9338-9cd3c0ffea50.png)

**Sobol method**

![image](https://user-images.githubusercontent.com/38532229/47207939-de1b1880-d38c-11e8-9827-b916eeed2a95.png)

**Morris method**

![image](https://user-images.githubusercontent.com/38532229/47207957-e8d5ad80-d38c-11e8-9c5d-030f02a76d91.png)

**FAST99 method**

![image](https://user-images.githubusercontent.com/38532229/47208002-030f8b80-d38d-11e8-8433-77f2fb2a6bb0.png)

It seems to me that this happens because the code doesn't take it into account.

**Sobol method**

https://github.com/NREL/OpenStudio-server/blob/053a6400874f464f149b87d22cef3235035f2ed3/docker/R/lib/sobol.R#L126

**Morris method**

https://github.com/NREL/OpenStudio-server/blob/053a6400874f464f149b87d22cef3235035f2ed3/docker/R/lib/morris.R#L149

**FAST99 method**

https://github.com/NREL/OpenStudio-server/blob/053a6400874f464f149b87d22cef3235035f2ed3/docker/R/lib/fast99.R#L159

**Comment by rHorsey** [comment]
tested by @brianlball
