### ISSUE TITLE
download mechanism for analysis finalization/initialization logs and related output

### ISSUE THREAD

**Issue by anyaelena** [NREL/OpenStudio-server#432]

**Comment by joseph-robertson** [comment]
I have a file, `/mnt/openstudio/server/analyses/ANALYSIS_ID/results_savings.csv`, on the web-background container that I'd like to be downloadable.

**Comment by rHorsey** [comment]
We need to document Joe's workaround someplace in the wiki.

**Comment by brianlball** [comment]
scripts show up in logs now
