### ISSUE TITLE
Incomplete datapoints are created causing server hang

### ISSUE THREAD

**Issue by brianlball** [NREL/OpenStudio-server#435]
The server will create incomplete datapoints which hang up the server.
There is a 503 error in the resque admin page.
Going into the resque admin page and clicking retry failed jobs will restart them and get the process going again.
debugging reveals adding Retry's to the RestClient calls in https://github.com/NREL/OpenStudio-server/blob/develop/server/app/jobs/dj_jobs/run_simulate_data_point.rb seems to alleviate the issue.

**Comment by brianlball** [comment]
testing in this branch looks successful so far
https://github.com/NREL/OpenStudio-server/tree/restclient_retry

**Comment by brianlball** [comment]
fixed in https://github.com/NREL/OpenStudio-server/pull/436

**Comment by nllong** [comment]
Brian, can we close this ticket since you said it was fixed in #436.
