### ISSUE TITLE
Failing datapoint initialization script does not cause the data point to error out

### ISSUE THREAD

**Issue by nllong** [NREL/OpenStudio-server#480]
If a worker initialization script fails, then the simulations still attempt to run.

The ideal situation would be to error the current simulation and also error out (remove from queue) all the remaining simulations on the current worker.

I'm am working on adding a test to the framework to demonstrate this issue, but will need to be run as a functional test due to the need for resque.

**Comment by brianlball** [comment]
@nllong  is this still an issue?

**Comment by nllong** [comment]
closing. If it pops up again we can reopen or create a new issue.
