### ISSUE TITLE
update to build/publish code in develop3 before merge into develop

### ISSUE THREAD

**Issue by anyaelena** [NREL/OpenStudio-server#504]
Develop3 branch currently set up for temporary publishing and testing paths.

Dockerfile, travis.yml, appveyor.yml, docker/deployment/scripts/deploy_docker.sh, ci/travis/setup.sh

**Comment by anyaelena** [comment]
Also updating to use .dmg instead of .zip for OSX installer.

**Comment by brianlball** [comment]
develop3 was merged.  can this get closed? @anyaelena

**Comment by anyaelena** [comment]
Yes.
