### ISSUE TITLE
Add support for OSW `file_paths` and `workflow.runner.findFile`

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio-server#540]
The OpenStudio CLI when running OSW supports passing in multiple `file_paths` for any kind of file, beyond seed models and weather files. This is useful among other things, for when a measure requires an external user specified file. This is supported in OpenStudio 2.0 and later with the `workflow.runner.findFile` method, as demonstrated in the ChangeBuildingLocation measure.

https://github.com/NREL/openstudio-common-measures-gem/blob/develop/lib/measures/ChangeBuildingLocation/measure.rb#L138-L145

PAT supports uploaded these files to the analysis zip, but it doesn't support adding `file_paths` to the datapoint OSW files. I have an issue filed for that here
https://github.com/NREL/OpenStudio-PAT/issues/87

I'm now working on projects where I make OSA files outside of a GUI and I'd like enable this functionality there, as a stepping stone to eventually adding it to PAT.
https://github.com/DavidGoldwasser/osw2osa

Here is what comes out of the out.osw on a run on OpenStudio Server. I haven't found a way to make use of the `files` directory in an analysis in conjunction with the OSW `file_paths`. I do think I can overload the weather or seeds directory, so maybe files just needs to have be added for the missing one directory up?

"/mnt/openstudio/analysis_370936a7-b9ad-40b1-bf6a-bb3c285f7ea3/data_point_0ab1f25b-8074-4440-aa89-43af4bc76d2d/generated_files",
"../weather",
"../seeds",
"../seed",
"./files",
"./weather",
"../../files",
"../../weather",
"./"

**Comment by jmarrec** [comment]
Permalink: https://github.com/NREL/openstudio-common-measures-gem/blob/916975bace57da4d784f7e73d85ea02eed15566c/lib/measures/ChangeBuildingLocation/measure.rb#L154-L165

**Comment by brianlball** [comment]
@DavidGoldwasser is this still a thing or did we fix it with https://github.com/NREL/OpenStudio-PAT/issues/87 ?
