### ISSUE TITLE
New Feature Request: Support for OS Server to provide concurrent project processing

### ISSUE THREAD

**Issue by chrisbalbach** [NREL/OpenStudio-server#618]
**Current Behavior :**
OS Server ‘projects' are limited to processing only one project at a time, on a given resource. OS server currently waits until the last datapoint in the current project has completed the compute **before** the next analysis begins on the next project in the project queue. 
 
**Desired Behavior :**
We would like OS Server to have the ability to (within the constraints of a defined cluster) parallelize concurrent OSPs, not just parallelize datapoints within a single OSP.  This will also have the effect of increasing the utilization of cluster resources (within resource constraints), when projects are submitted. 
 
**Rationale**: 
This feature will both improve the cost effectiveness of HPC resources and reduce the associated run times related to project queuing. This should lead to improved OS server adoption for application use-cases where multiple OSP are being submitted to a single instance of OS Server, nearly simultaneously (regardless of the number of datapoints in each project).

Specifically, this feature will make OS Server a more logical deployment choice for OS Based solutions where minimization of "roundtrip" times for[ submitting inputs and generating results/analysis] are needed. This is particularly important when displacing current residential savings calculation methodologies such as spreadsheet based tools, etc. (where speed is valued as much, if not more, than accuracy) with OS/E+ model based approaches.

**Comment by tijcolem** [comment]
Cross listed here:  https://github.com/NREL/openstudio-server-helm/issues/23 & https://github.com/NREL/openstudio-server-helm/pull/24

The details on the change are in the PR,  but after looking into the queuing design of sever, this functionality was already supported but not enabled as the web-background service had a one resque worker by default which resulted in one project/analysis being ran at a time. Simply adding in additional web-background / resque worker jobs increases the number of projects that are processed.  Changes should happen on k8s/helm side vs server code.

**Comment by tijcolem** [comment]
Closed via https://github.com/NREL/openstudio-server-helm/pull/24

**Comment by brianlball** [comment]
https://github.com/NREL/OpenStudio-server/pull/755
