### ISSUE TITLE
Worker and web nodes at scale 

### ISSUE THREAD

**Issue by tijcolem** [NREL/OpenStudio-server#645]
Enhancement request

Worker nodes (pods in k8s) have their own local storage to process simulations. There are couple of issues related to this, especially at scale. 

1 ) The initialization script that runs before the simulation starts, typically fetches custom gems from either rubygems or git. Some of these (e.g. standards) can be data intensive and slow down the process as it has to do this n-times for n-workers. 

2 ) The simulation output and reports get sent the web via API. At scale, this can overload the web if not configured properly (giving it more resources in terms of cpu and mem) and can cause web failures. 

Some options: 

1 ) Have the init script run only once and then provide a read only mount to worker pods.  
2 ) Scale the web pod, or look into using shared writable volume (existing nfs) to write to disk vs sending via API.  
3 ) Have custom cloud setups for very large runs (200+ workers) that vertically scale the web node. 

This can also be discussed on https://github.com/NREL/OpenStudio-server-helm

**Comment by wenyikuang** [comment]
Here I am, just a comment to pop out my name without any really message.

**Comment by brianlball** [comment]
We have made many improvements for large scale sim support and have run >3Million on AWS EKS and some of those help address some of these symptoms.
I'm going to close this but we can always reopen if the need arises.
