### ISSUE TITLE
Web admin panel not showing cli version

### ISSUE THREAD

**Issue by tijcolem** [NREL/OpenStudio-server#648]
As posted on https://unmethours.com/question/70690/openstudio-cloud-management-console-shows-openstudio-cli-version-error/ the GUI is not reporting the version of the OpenStudio CLI.  

I think it's a just a minor fix for this in the code.  

https://github.com/NREL/OpenStudio-server/blob/develop/server/app/views/admin/index.html.erb#L75

https://github.com/NREL/OpenStudio-server/blob/develop/server/app/controllers/admin_controller.rb#L45

**Comment by brianlball** [comment]
in oscli_cmd: ENV['OPENSTUDIO_EXE_PATH'] is not set in the web container.  so, https://github.com/NREL/OpenStudio-server/blob/develop/server/app/lib/utility/oss.rb#L22 gets raised.  then oscli_cmd gets set to cmd + oscli_bundle https://github.com/NREL/OpenStudio-server/blob/develop/server/app/lib/utility/oss.rb#L36.  the bundle commands run in the backtick shell https://github.com/NREL/OpenStudio-server/blob/develop/server/app/controllers/admin_controller.rb#L46 are run with the user 'nobody', so there is no HOME env and bundler cant make a tmp dir.  

seems like the easiest fix is to just set the ENV['OPENSTUDIO_EXE_PATH'] in the Dockerfile https://github.com/NREL/OpenStudio-server/blob/cli_version/Dockerfile#L130 to the openstudio.exe install location
