### ISSUE TITLE
Rearrange web dashboard analysis order

### ISSUE THREAD

**Issue by anchapin** [NREL/OpenStudio-server#718]
When there is more than one analysis submitted to an openstudio-server, the last analysis to be submitted is always at the top of the list. However, the running analysis is at the bottom and the pie chart and started, queued, completed, NA counts are hidden.

I suggest having the currently running analysis always pinned to the top.

**Comment by JanghyunJK** [comment]
@brianlball I think we really need this (based on what I'm hearing) to run things faster in AWS?
