### ISSUE TITLE
Allow OS Cloud Management Console on AWS Instance stop/restart

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-server#85]
I was hoping that I could stop the OpenStudio-Server AWS Instance and later restart it to get back to the OS Cloud Management Console in order to view datapoints, download files, etc. However, upon restarting the instance and trying to connect, I get:

![os_error](https://cloud.githubusercontent.com/assets/5861765/17113958/15e685de-526a-11e6-9d45-5ff27ccc89ea.png)

**Comment by brianlball** [comment]
you lose the EBS mount when you shut it down.  We've wanted to make functionality that will save the mount and move it to S3 where you can start up a cheaper Sever navigation console but we've not had the time or $ to make that happen.  

Solution now is to Admin/Backup Database and then startup a cheaper server and load the backup file.  You can view the database, but you wont have access to the .zip files.
