### ISSUE TITLE
AWS instances running out of space

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-server#91]
I can pretty easily run into situations where the AWS instance runs out of space. It only takes ~20k datapoints for this to occur. This is when using the c3.8xlarge instance type with 640GB of space for the server instance. I'm not sure offhand how much of that space /mnt/openstudio has available. However, I seem to recall that it's the mongo log file that eats up the majority of space.

FWIW, I'm using the ServerDirectoryCleanup reporting measure in our analysis, which helps, but only allows us to get so far.

I'm happy to reproduce the problem and provide more information if it's helpful. Just let me know. But this is a pretty big issue for our BPA deliverable of our PNW ResStock tool.

**Comment by rHorsey** [comment]
This is actually great news - it means that adding in the garbage collection looks to have worked. Before the server would jam up prior to the fs running out of room. @shorowit When do you need this fixed by?

**Comment by shorowit** [comment]
@rHorsey Ideally by the middle of December.

**Comment by nllong** [comment]
I know that the docker stuff is really green right now, but this may help as long as you can currently run your analysis on one machine (or work on documenting docker-swarm). 

The starting of the docker cluster has a root-size param that we can set (https://github.com/NREL/OpenStudio-server/blob/dockerize/docker/README.md#starting-cluster)

**Comment by rHorsey** [comment]
I'm closing this in favor of https://github.com/NREL/OpenStudio/issues/2605
